### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__C)

### ISSUE THREAD

**Issue by Elaine0823** [dliu5812/DDF#3]
Hello，
    I'm trying to run your code, but I'm having the following problem:
![image](https://user-images.githubusercontent.com/77908581/171994210-fd15367b-aaee-4022-b10c-45d30db6dfd5.png)
    Could you please tell me how to solve this problem. Thanks!

**Comment by drickzsy** [comment]
> Hello， I'm trying to run your code, but I'm having the following problem: ![image](https://user-images.githubusercontent.com/77908581/171994210-fd15367b-aaee-4022-b10c-45d30db6dfd5.png) Could you please tell me how to solve this problem. Thanks!

Same question!
Could you please tell me if you have solved it or not?

**Comment by xiojioji** [comment]
Same question!
Could you please tell me if you have solved it or not?
