### ISSUE TITLE
cityscapes_car

### ISSUE THREAD

**Issue by youaloha** [dliu5812/DDF#4]
Hello,Can you offer the cityscapes_car database? thank you!

**Comment by dliu5812** [comment]
Hi

The cityscapes_car database is similar to the original cityscape dataset. Following previous settings in UDA object detection, we only use the objects under the 'car' category to train the model, while ignoring all the rest objects in other categories.

You can find the whole cityscape dataset in the:

https://drive.google.com/file/d/1mA0L5-1U_Vo-S8-cv12QBmhgG9FFf6nf/view
